version: '3'

services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"

  uwsgi:
    restart: always
    build: ./app
    volumes:
      - ./app:/app/
    ports:
      - "3031:3031"
    command: uwsgi --ini /app/uwsgi.ini
    environment:
      TZ: "Asia/Tokyo"
